var regexForMainURL = /.*\/\/.+?\//;
var currentURL = document.URL;
var newURL = currentURL.replace(regexForMainURL, "http://cn.xcv58.com/");
var greeting = "<h1>You may visit link from my Chinese Blog</br>redirect to in 3 seconds:</br>";
// var xmlHttp = new XMLHttpRequest();
// xmlHttp.open( "GET", newURL );
// xmlHttp.send( null );
// var response = xmlHttp.responseText;
document.getElementById("cn-xcv58-com").innerHTML = greeting + "<a href='" + newURL + "'>" + newURL + "</a></h1>";
setInterval(function () {window.location = newURL}, 5000);
